@startuml
class User{
    int user_ID
    String name
    String username
    String password
    String email
    ArrayList<Integer> team_IDs
}

class Event{
    int event_ID
    User host
    String date
    String title
    String description
    ArrayList<participant> participants
    Arraylist<Teams> teams

    String getTeamNames()
}

class participant{
    int participant_ID
    User participant
    ParticipantStatus status
}

enum ParticipantStatus{
    hasentAnswered
    maybe
    going
    cantGo
}

class NewsFeedMessage{
    int NewsFeedMessage_ID
    String title
    String date
    ArrayList<Team> teams
    User sender
    String messages
    ArrayList<NewsFeedMessageComment>
}

class NewsFeedMessageComment{
    User sender
    String date
    String comment
}

class Team{
    int team_ID
    String name
    String description
    User createrOfTeam
    ArrayList<User> teamMembers
}

Event "many" *-- "many" Team

@enduml